### ISSUE TITLE
請問海外也可使用嗎?

### ISSUE THREAD

**Issue by twentyoneisawesome** [hushenghao/music#3]
試著從台灣呼叫api, 某些歌曲會無法撥放...
ex. songmid = '000D9SKp2ZFkN2'
謝謝

**Comment by hushenghao** [comment]
你可以尝试使用[网页版](http://music.sonimei.cn/)的，和客户端使用的api相同。

**Comment by twentyoneisawesome** [comment]
謝謝hushenghao.
我從網頁版搜尋'wannaone'. 結果是無法撥放.
